version: '3'
services:
  discord-api:
    build:
      context: .
      dockerfile: src/Dockerfile
      target: base
      args:
        root_path: '/'
        api_port: 3000
    command: uvicorn src.core.server:app --host 0.0.0.0 --reload --reload-include src/*
    container_name: discord-api
    volumes:
      - ./src:/project/src:rw
    env_file:
      - src/.env
    ports:
      - 3000:3000
    networks:
      - botdetector-network

networks:
  botdetector-network:
