version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: mysql-discord:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_bot_buster
    volumes:
      - ./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./database/mount:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - botdetector-network

networks:
  botdetector-network:

